name: Update Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Generate Doxygen documentation
        run: doxygen docs/Doxyfile

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update Doxygen documentation"
          git push origin main
