name: Update Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: |
          find docs/ -mindepth 1 ! -name 'Doxyfile' -exec rm -rf {} +
          doxygen docs/Doxyfile
          cd docs/html && mv * ../ && cd ../..

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git diff --cached --quiet || (git commit -m "Update Doxygen documentation" && git push)

