name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  ROS_BUILD_DIR: JetRacer

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install ROS
        run: |
          sudo apt update
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update && sudo apt install -y ros-humble-desktop

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ros-install
          path: JetRacer/install

      - name: Run Tests
        run: |
          source /opt/ros/humble/setup.bash
          cd $ROS_BUILD_DIR
          source ./install/setup.bash
          colcon test --ctest-args tests --packages-skip camera_ros --executor sequential
          colcon test-result --all --verbose

